//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuickFood.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order_Detail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order_Detail()
        {
            this.Topping_Order = new HashSet<Topping_Order>();
        }
    
        public long ID { get; set; }
        public Nullable<long> Food_ID { get; set; }
        public Nullable<int> Count { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<long> Order_ID { get; set; }
    
        public virtual Food Food { get; set; }
        public virtual Order Order { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Topping_Order> Topping_Order { get; set; }
    }
}
