//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuickFood.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Topping_Order
    {
        public long ID { get; set; }
        public Nullable<long> Topping_ID { get; set; }
        public Nullable<long> OrderDetail_ID { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<decimal> Price { get; set; }
    
        public virtual Order_Detail Order_Detail { get; set; }
        public virtual Topping Topping { get; set; }
    }
}
